// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package message

import "strconv"

type Action int8

const (
	ActionUp     Action = 0
	ActionDown   Action = 1
	ActionMove   Action = 2
	ActionClear  Action = 3
	ActionCursor Action = 4
	ActionCancel Action = 5
)

var EnumNamesAction = map[Action]string{
	ActionUp:     "Up",
	ActionDown:   "Down",
	ActionMove:   "Move",
	ActionClear:  "Clear",
	ActionCursor: "Cursor",
	ActionCancel: "Cancel",
}

var EnumValuesAction = map[string]Action{
	"Up":     ActionUp,
	"Down":   ActionDown,
	"Move":   ActionMove,
	"Clear":  ActionClear,
	"Cursor": ActionCursor,
	"Cancel": ActionCancel,
}

func (v Action) String() string {
	if s, ok := EnumNamesAction[v]; ok {
		return s
	}
	return "Action(" + strconv.FormatInt(int64(v), 10) + ")"
}
